categories:
- Visualization
description: 'Circular Genome Viewer'
long_description: |
  CGView is a Java package for generating high quality, zoomable maps of circular genomes.
  Its primary purpose is to serve as a component of sequence annotation pipelines, as a means of generating visual output suitable for the web.
name: cgview
owner: dfornika
remote_repository_url: https://github.com/dfornika/galaxy/tree/master/tools/cgview
homepage_url: http://wishart.biology.ualberta.ca/cgview
type: unrestricted
