categories:
- Data Managers
description: Data Manager for building kma indexes
homepage_url: ''
long_description: |
    Data Manager for building kma indexes.
name: data_manager_kma_index_builder
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_kma_index_builder
type: unrestricted
