categories:
- Sequence Analysis
description: 'A complete suite for gene-by-gene schema creation and strain identification'
long_description: |
  chewBBACA is a comprehensive pipeline including a set of functions for the creation and validation of
  whole genome and core genome MultiLocus Sequence Typing (wg/cgMLST) schemas, providing an allele calling
  algorithm based on Blast Score Ratio that can be run in multiprocessor settings and a set of functions
  to visualize and validate allele variation in the loci.
name: suite_chewbbaca
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/chewbbaca
homepage_url: https://github.com/B-UMMI/chewBBACA
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "chewBBACA tool suite: {{ tool_name }}"
suite:
  name: "suite_chewbbaca"
  description: "chewBBACA tools"
  type: repository_suite_definition
